/*
 * LaunchDarkly REST API
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 5.1.0
 * Contact: support@launchdarkly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.launchdarkly.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.launchdarkly.api.model.Link;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DependentFlagEnvironmentLinks
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-21T16:19:08.589Z")



public class DependentFlagEnvironmentLinks {
  @SerializedName("self")
  private Link self = null;

  @SerializedName("flagLink")
  private Link flagLink = null;

  public DependentFlagEnvironmentLinks self(Link self) {
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @ApiModelProperty(value = "")
  public Link getSelf() {
    return self;
  }

  public void setSelf(Link self) {
    this.self = self;
  }

  public DependentFlagEnvironmentLinks flagLink(Link flagLink) {
    this.flagLink = flagLink;
    return this;
  }

   /**
   * Get flagLink
   * @return flagLink
  **/
  @ApiModelProperty(value = "")
  public Link getFlagLink() {
    return flagLink;
  }

  public void setFlagLink(Link flagLink) {
    this.flagLink = flagLink;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DependentFlagEnvironmentLinks dependentFlagEnvironmentLinks = (DependentFlagEnvironmentLinks) o;
    return Objects.equals(this.self, dependentFlagEnvironmentLinks.self) &&
        Objects.equals(this.flagLink, dependentFlagEnvironmentLinks.flagLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, flagLink);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DependentFlagEnvironmentLinks {\n");
    
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    flagLink: ").append(toIndentedString(flagLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

