/*
 * LaunchDarkly REST API
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 5.0.2
 * Contact: support@launchdarkly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.launchdarkly.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.launchdarkly.api.model.UnboundedSegmentTargetChanges;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UnboundedSegmentTargetsBody
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-22T22:04:52.396Z")



public class UnboundedSegmentTargetsBody {
  @SerializedName("included")
  private UnboundedSegmentTargetChanges included = null;

  @SerializedName("excluded")
  private UnboundedSegmentTargetChanges excluded = null;

  public UnboundedSegmentTargetsBody included(UnboundedSegmentTargetChanges included) {
    this.included = included;
    return this;
  }

   /**
   * Get included
   * @return included
  **/
  @ApiModelProperty(value = "")
  public UnboundedSegmentTargetChanges getIncluded() {
    return included;
  }

  public void setIncluded(UnboundedSegmentTargetChanges included) {
    this.included = included;
  }

  public UnboundedSegmentTargetsBody excluded(UnboundedSegmentTargetChanges excluded) {
    this.excluded = excluded;
    return this;
  }

   /**
   * Get excluded
   * @return excluded
  **/
  @ApiModelProperty(value = "")
  public UnboundedSegmentTargetChanges getExcluded() {
    return excluded;
  }

  public void setExcluded(UnboundedSegmentTargetChanges excluded) {
    this.excluded = excluded;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnboundedSegmentTargetsBody unboundedSegmentTargetsBody = (UnboundedSegmentTargetsBody) o;
    return Objects.equals(this.included, unboundedSegmentTargetsBody.included) &&
        Objects.equals(this.excluded, unboundedSegmentTargetsBody.excluded);
  }

  @Override
  public int hashCode() {
    return Objects.hash(included, excluded);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnboundedSegmentTargetsBody {\n");
    
    sb.append("    included: ").append(toIndentedString(included)).append("\n");
    sb.append("    excluded: ").append(toIndentedString(excluded)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

