/*
 * LaunchDarkly REST API
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 1.0.7
 * Contact: support@launchdarkly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets NonOwnerRole
 */
@JsonAdapter(NonOwnerRole.Adapter.class)
public enum NonOwnerRole {
  
  WRITER("writer"),
  
  READER("reader"),
  
  ADMIN("admin");

  private String value;

  NonOwnerRole(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static NonOwnerRole fromValue(String text) {
    for (NonOwnerRole b : NonOwnerRole.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<NonOwnerRole> {
    @Override
    public void write(final JsonWriter jsonWriter, final NonOwnerRole enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public NonOwnerRole read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return NonOwnerRole.fromValue(String.valueOf(value));
    }
  }
}

