/*
 * LaunchDarkly REST API
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@launchdarkly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.PatchDelta;
import io.swagger.client.model.Webhook;
import io.swagger.client.model.WebhookPost;
import io.swagger.client.model.Webhooks;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebhooksApi
 */
@Ignore
public class WebhooksApiTest {

    private final WebhooksApi api = new WebhooksApi();

    
    /**
     * Delete a webhook by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteWebhookTest() throws ApiException {
        String webhookId = null;
        api.deleteWebhook(webhookId);

        // TODO: test validations
    }
    
    /**
     * Get a webhook by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWebhookTest() throws ApiException {
        String webhookId = null;
        Webhook response = api.getWebhook(webhookId);

        // TODO: test validations
    }
    
    /**
     * Fetch a list of all webhooks
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWebhooksTest() throws ApiException {
        Webhooks response = api.getWebhooks();

        // TODO: test validations
    }
    
    /**
     * Modify a webhook by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchWebhookTest() throws ApiException {
        String webhookId = null;
        List<PatchDelta> patchDelta = null;
        api.patchWebhook(webhookId, patchDelta);

        // TODO: test validations
    }
    
    /**
     * Create a webhook
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postWebhookTest() throws ApiException {
        WebhookPost webhookPost = null;
        api.postWebhook(webhookPost);

        // TODO: test validations
    }
    
}
